### ISSUE TITLE
The build is broken...

### ISSUE THREAD

**Issue by khallebal** [jsbronder/sff#1]
I tried to build it with gcc-8.3.0 under haiku i got the following error:

```sh
/boot/home/Desktop/sff/qvterm/qvterm.cpp: In member function 'int QVTerm::settermprop(VTermProp, VTermValue*)':
/boot/home/Desktop/sff/qvterm/qvterm.cpp:739:45: error: no matching function for call to 'QVTerm::iconTextChanged(VTermStringFragment&)'
             emit iconTextChanged(val->string);
                                             ^
In file included from /boot/home/Desktop/sff/qvterm/qvterm.cpp:1:
/boot/home/Desktop/sff/qvterm/qvterm.hpp:64:10: note: candidate: 'void QVTerm::iconTextChanged(QString)'
     void iconTextChanged(QString iconText);
          ^~~~~~~~~~~~~~~
/boot/home/Desktop/sff/qvterm/qvterm.hpp:64:10: note:   no known conversion for argument 1 from 'VTermStringFragment' to 'QString'
/boot/home/Desktop/sff/qvterm/qvterm.cpp:742:42: error: no matching function for call to 'QVTerm::titleChanged(VTermStringFragment&)'
             emit titleChanged(val->string);
                                          ^
In file included from /boot/home/Desktop/sff/qvterm/qvterm.cpp:1:
/boot/home/Desktop/sff/qvterm/qvterm.hpp:65:10: note: candidate: 'void QVTerm::titleChanged(QString)'
     void titleChanged(QString title);
          ^~~~~~~~~~~~
/boot/home/Desktop/sff/qvterm/qvterm.hpp:65:10: note:   no known conversion for argument 1 from 'VTermStringFragment' to 'QString'

```
How can i fix this?

**Comment by jsbronder** [comment]
You're using a newer version of libvterm than the one bundled.  Make sure you update the submodule.

Note that while I am using this terminal daily, it's still pretty experimental until I at least get the features I'm looking for and can't find elsewhere (keyboard selection mode, location marking, performance on par with other terminals for instance) I'm not trying to closely track libvterm.  If I get to feature complete, I'll want to remove the bundling entirely and just use libvterm as provided by whatever distribution.

**Comment by khallebal** [comment]
Sorry  i forgot to mention that there wasn't any bundeld libvterm with your source code, and the build    
system failed to download one, so i used the one from trunk which gave me this error.
But i'd love to have it running in haiku.

**Comment by sskras** [comment]
@jsbronder commented [on Apr 2, 2020](https://github.com/jsbronder/sff/issues/1#issuecomment-607952634):

> You're using a newer version of libvterm than the one bundled.

Are you willing to push your patches upstream?
https://github.com/neovim/libvterm/compare/master...jsbronder:libvterm:sff

Or, in general, are you going to work with the upstream trunk anytime soon? Which would be:
http://bazaar.leonerd.org.uk/c/libvterm/
https://www.leonerd.org.uk/code/libvterm/

Thanks in advance.

**Comment by jsbronder** [comment]
> Or, in general, are you going to work with the upstream trunk anytime soon? Which would be: http://bazaar.leonerd.org.uk/c/libvterm/ https://www.leonerd.org.uk/code/libvterm/

I did and never heard back, for example:

```
From: Justin Bronder <jsbronder@cold-front.org>
Date: Mon, 11 May 2020 19:40:59 -0400
To: leonerd@leonerd.org.uk
Cc: Justin Bronder <jsbronder@cold-front.org>
Subject: [PATCH] Use appropriate pen when reallocating screen cell buffers
X-Mailer: git-send-email 2.24.1
```

Feel free to see if you have better luck ;)

**Comment by sskras** [comment]
Thanks for the update. Will try.
