### ISSUE TITLE
Cross-platform PTY backend

### ISSUE THREAD

**Issue by kafeg** [jsbronder/sff#2]
Hey! I would like to propose you to use my cross-platform PTY/Qt backend as a base for your terminal project. With it, you can support Linux/MacOS/Windows both with the same interface.

If you are interested, please check out it here: https://github.com/kafeg/ptyqt

**Comment by jsbronder** [comment]
Cool, looks nice!  I'll take a closer look once I've added and stabilized some newer features I want in sff and try to bring it in.  Right now I'm still (very slowly) experimenting with what this project might end up looking like so I don't want to add another dependency.

**Comment by kafeg** [comment]
Of course, just suggestion)
