### ISSUE TITLE
How to compile under windows? Thanks

### ISSUE THREAD

**Issue by zhangfq-chemistry** [jsbronder/sff#3]

**Comment by jsbronder** [comment]
If you get it compiling under windows, I'd be interested in seeing the patches.  But there's a lot of posix/linux specific calls in here so I wouldn't be surprised if it was a lot of effort.

**Comment by sskras** [comment]
The @midipix project may come in handy:
https://midipix.org/#sec-midipix
https://sysdeer.net/

But they still doesn't do public distribution of their binaries, so one would need to built it by oneself on Linux:
https://github.com/lalbornoz/midipix_build#2-building-and-deployment
