### ISSUE TITLE
Successfully running on an eReader!

### ISSUE THREAD

**Issue by tux-linux** [jsbronder/sff#4]
Hello,

Just to let you know... we have ported your software to [InkBox OS](https://github.com/Kobo-InkBox/inkbox) as an 'user app' and it works quite well ;)
Thanks for making the only, or one of the only terminal emulators that use pure C++ Qt and is mentally sane to cross-compile for ARM from another non-native host.

https://github.com/Kobo-InkBox/sff

![PXL_20230628_004616428](https://github.com/jsbronder/sff/assets/63172576/aa532929-3a9f-4767-a92c-2c6db2039334)

**Comment by jsbronder** [comment]
Hah, very cool!  Glad you found it useful.

**Comment by tux-linux** [comment]
https://www.youtube.com/watch?v=7piH2415cnY
